spring:
  security.oauth2.client:
    registration:
      google:
        client-id: 187926156000-1q9fjvkoooen5r13nplvr5tk9sj9tcj7.apps.googleusercontent.com
        client-secret: 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
logging:
  level:
    org.springframework.security: DEBUG        
server:
  forward-headers-strategy: framework      
